// apps/next-app/src/features/dashboard/components/Dashboard.tsx
"use client"

import {
	Card,
	CardContent,
	CardHeader,
	CardTitle,
} from "@/components/ui/card"
import { DataTable } from "@/components/ui/data-table"

import { Employee } from "@/types"

import { columns, stats } from "../mocks"

type DashboardType = {
	data: Employee[];
}

const Dashboard = ({ data }: DashboardType) => {
	return (
		<div className="container mx-auto px-2 py-10 space-y-4">
			<section className="flex flex-col items-start gap-2 border-b border-border/40 py-8 dark:border-border md:py-10 lg:py-12">
				<div className="container">
					<h1 className="text-3xl font-bold leading-tight tracking-tighter md:text-4xl lg:leading-[1.1]">Compliance Tracker Dashboard</h1>
					<p className="max-w-2xl text-lg font-light text-foreground">Monitor training progress across your team. Quickly identify employees who are on track, behind, or yet to start their required programs.</p>
				</div>
			</section>
			<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
				{stats?.map((stat, index) => (
					<Card key={index}>
						<CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
							<CardTitle className="text-sm font-medium">
								{stat.title}
							</CardTitle>
						</CardHeader>
						<CardContent>
							<div className="text-2xl font-bold">{stat.value}</div>
							<p className="text-xs text-muted-foreground">
								{stat.description}
							</p>
						</CardContent>
					</Card>
				))}
			</div>
			<div>
				<DataTable columns={columns} data={data} />
			</div>
		</div>
	)
}

export default Dashboard

// apps/angular-app/src/app/features/dashboard/dashboard.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CardComponent } from '../../shared/components/ui/card/card.component';
import { DashboardService } from './dashboard.service';
import { UsersData } from '@/app/shared/components/models/dashboard.model';

@Component({
  selector: 'app-dashboard',
  imports: [CommonModule, FormsModule, CardComponent],
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent {
  dashboardStats: { title: string; description: string; value: number }[] = [
    {
      title: 'Total Employees',
      value: 0,
      description:
        'The total number of employees being tracked for compliance.',
    },
    {
      title: 'Trainings Completed',
      value: 0,
      description:
        'Employees who have successfully completed all required trainings.',
    },
    {
      title: 'Trainings In Progress',
      value: 0,
      description: 'Employees actively working on their required trainings.',
    },
    {
      title: 'Trainings Not Started',
      value: 0,
      description: 'Employees who have not started their required trainings.',
    },
  ];

  loading: boolean = true;

  constructor(private dashboardService: DashboardService) {}

  ngOnInit(): void {
    this.dashboardService.getAllActiveUsers().subscribe({
      next: (data: UsersData[]) => {
        data.forEach((item) => {
          const { node } = item;
          this.dashboardStats[0]['value'] = data.length;
          this.dashboardStats[1]['value'] +=
            node.assigned_learning_resourceCollection.edges.filter(
              (resource) =>
                resource.node.started_at && resource.node.completed_at
            ).length;
          this.dashboardStats[2]['value'] +=
            node.assigned_learning_resourceCollection.edges.filter(
              (resource) =>
                resource.node.started_at && !resource.node.completed_at
            ).length;
          this.dashboardStats[3]['value'] +=
            node.assigned_learning_resourceCollection.edges.filter(
              (resource) =>
                resource.node.started_at === null &&
                resource.node.completed_at === null
            ).length;
        });
        this.loading = false;
      },
      error: (err) => {
        console.error('Error fetching users data', err);
        this.loading = false;
      },
    });
  }
}

<div class="container mx-auto px-2 py-10 space-y-4">
  <section
    class="flex flex-col items-start gap-2 border-b border-border/40 py-8 dark:border-border md:py-10 lg:py-12"
  >
    <div class="container">
      <h1
        class="text-3xl font-bold leading-tight tracking-tighter md:text-4xl lg:leading-[1.1]"
      >
        Compliance Tracker Dashboard
      </h1>
      <p class="max-w-2xl text-lg font-light text-foreground">
        Monitor training progress across your team. Quickly identify employees
        who are on track, behind, or yet to start their required programs.
      </p>
    </div>
  </section>
  <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
    <spartan-card
      *ngFor="let stat of dashboardStats"
      [title]="stat.title"
      [footer]="stat.description"
      ><div class="text-2xl font-bold">
        {{ stat.value }}
      </div></spartan-card
    >
  </div>
</div>
